#! /bin/sh
# /etc/init.d/dyndns

### BEGIN INIT INFO
# Provides:          noip2
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# The below steps will allow the script to be a service command
# export $PATH=/usr/bin
# ln -s /etc/init.d/dyndns /usr/bin/dyndns

#Variables
DATE=$(date)

case "$1" in
  start)
    echo "$DATE Startting noip2" | tee -a /var/log/pilog
    /usr/local/bin/noip2
    echo "$DATE noip2 started $(pidof noip2)" | tee -a /var/log/pilog
    ;;

  stop)
    echo "$DATE noip2 stopped PID=$(pidof noip2)" | tee -a /var/log/pilog
    killall noip2
    ;;

  restart)
    echo "$DATE noip2 stopped PID=$(pidof noip2)" | tee -a /var/log/pilog
    killall noip2
    /usr/local/bin/noip2
    echo "$DATE noip2 re-started PID=$(pidof noip2)"  | tee -a /var/log/pilog
    ;;

  status)
    if ps aux | grep [n]oip2 > /dev/null
     then
      echo "PID=$(pidof noip2) noip2 is running..."
     else
      echo "noip2 is stopped..."
    fi
    ;;

  *)
    echo "Usage: /etc/init.d/noip2 {start|stop|restart|status}"
    exit 1
    ;;

esac

exit 0
