#! /bin/sh
# /etc/init.d/dyndns
#
#
### BEGIN INIT INFO
# Provides: noip2
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Starts noip2
### END INIT INFO

# The lsb init functions
. /lib/lsb/init-functions

# Variables
DATE=$(date)
NAME=noip2
DAEMON=/usr/local/bin/noip2
PID=$(pidof noip2)

case "$1" in

 start)

   if [ -e $DAEMON ]; then
    status_of_proc $DAEMON "$NAME" && status="0" || status="$?"
   if [ $status = "0" ]; then
    exit
   else
    start-stop-daemon -S -q -o -x $DAEMON
    log_success_msg "$NAME ($(pidof noip2)) is running"
    echo "$DATE noip2 $(pidof noip2) started" >> /home/pi/pittl/log
   fi
   fi

;;

 stop)

  if [ -e $DAEMON ]; then
   status_of_proc $DAEMON "$NAME" && status="0" || status="$?"
   if [ "$status" = 0 ]; then
    start-stop-daemon -K -q -o -n $NAME
    log_success_msg "$NAME is stopped"
    echo "$DATE noip2 $PID stopped" >> /home/pi/pittl/log
   fi
  else
   log_daemon_msg "$NAME process is not running"
  fi

;;

 restart)

  $0 stop && sleep 2 && $0 start

;;

 status)

 status_of_proc $DAEMON "$NAME ($(pidof noip2)) process"

;;

*)

 echo "Usage: $0 {start|stop|restart|status}"
 exit 2

;;

esac
