#! /bin/sh
# /etc/init.d/pimet
#
### BEGIN INIT INFO
# Provides:          Kismet on boot
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

# put this script in the /home/pi/scripts folder
# run sudo ln -s /home/pi/scripts/pimet /etc/init.d/pimet
# sudo update-rc.d pimet defaults

# The below steps will allow the script to run when in root
# sudo ln -s /home/pi/pittl/noip /usr/local/bin/noip

# The lsb init functions
. /lib/lsb/init-functions

#variables
DATE=$(date)
NAME=kismet_server
DAEMON='/usr/local/bin/kismet_server --daemonize'
PID=$(pidof kismet_server)
LOG=/var/log/pilog

case "$1" in

  start)
   airmon-ng check kill
   airmon-ng start wlan0
   $DAEMON
   #/usr/local/bin/kismet_server --daemonize
   echo "$DATE $NAME started PID=$(pidof kismet_server)" | tee -a $LOG
   ;;

  stop)
   killall kismet_server
   airmon-ng stop wlan0mon
   service ifplugd start
   echo "$DATE $NAME stopped" | tee -a $LOG
   ;;

 status)
  status_of_proc $NAME "$NAME $PID process"
  ;;

 *)
  echo "Usage: /usr/local/bin/kismet_server {start|stop|status}"
 ;;

esac

exit 0
